; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = 0_master

[env:0_master]
platform = teensy
board = teensy41
framework = arduino
build_src_filter = +<0_master/*> -<1_slave_wheel/*> -<2_slave_arm/*> -<3_slave_lift/*> -<4_slave_sensor/*> -<5_slave_laser/*>

[env:1_slave_wheel]
platform = ststm32
board = blackpill_f411ce
framework = arduino
monitor_speed = 115200
build_src_filter = +<1_slave_wheel/*> -<0_master/*> -<2_slave_arm/*> -<3_slave_lift/*> -<4_slave_sensor/*> -<5_slave_laser/*>
upload_protocol = stlink

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON

[env:2_slave_arm]
platform = ststm32
board = blackpill_f411ce
framework = arduino
monitor_speed = 115200
build_src_filter = +<2_slave_arm/*> -<0_master/*> -<1_slave_wheel/*> -<3_slave_lift/*> -<4_slave_sensor/*> -<5_slave_laser/*>
upload_protocol = stlink

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON

[env:3_slave_lift]
platform = ststm32
board = blackpill_f411ce
framework = arduino
monitor_speed = 115200
build_src_filter = +<3_slave_lift/*> -<0_master/*> -<1_slave_wheel/*> -<2_slave_arm/*> -<4_slave_sensor/*> -<5_slave_laser/*>
upload_protocol = stlink

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON

[env:4_slave_sensor]
platform = ststm32
board = blackpill_f411ce
framework = arduino
monitor_speed = 115200
build_src_filter = +<4_slave_sensor/*> -<0_master/*> -<1_slave_wheel/*> -<2_slave_arm/*> -<3_slave_lift/*> -<5_slave_laser/*>
upload_protocol = stlink

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON

[env:5_slave_laser]
platform = ststm32
board = blackpill_f411ce
framework = arduino
monitor_speed = 115200
build_src_filter = +<5_slave_laser/*> -<0_master/*> -<1_slave_wheel/*> -<2_slave_arm/*> -<3_slave_lift/*> -<4_slave_sensor/*>
upload_protocol = stlink

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON

[env:test_lift_encoder]
platform = ststm32
board = blackpill_f411ce
framework = arduino
monitor_speed = 115200
build_src_filter = +<test_lift_encoder/*> -<0_master/*> -<1_slave_wheel/*> -<2_slave_arm/*> -<3_slave_lift/*> -<4_slave_sensor/*> -<5_slave_laser/*>
upload_protocol = stlink

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
